# Scratch 

A notebook for wxploring Python, Jupyter, etc.

In [21]:
D = 100
d = 50

In [22]:
D

100

In [23]:
d

50

In [24]:
whos


Variable   Type       Data/Info
-------------------------------
D          int        100
Lx         int        3
d          int        50
dx         float      0.5
np         module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
numpy      module     <module 'numpy' from '/op<...>kages/numpy/__init__.py'>
nx         int        6
x          ndarray    6: 6 elems, type `float64`, 48 bytes
x1         ndarray    7: 7 elems, type `float64`, 56 bytes


In [25]:
import numpy as np

    Next, set up the model grid with a NumPy aray

In [26]:
Lx = 8
dx = 0.5
x = np.arange(start=0, stop=Lx, step = dx)
nx =  len(x)

In [27]:
nx

16

In [28]:
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5])

In [29]:
x1 = np.linspace(start=0, stop=Lx, num=7, endpoint =True) 

In [30]:
x1

array([0.        , 1.33333333, 2.66666667, 4.        , 5.33333333,
       6.66666667, 8.        ])

In [31]:
C = np. zeros_like(x)
C_left =  500
C_right =  0
C[x <= Lx//2] = C_left
C[x > Lx//2] = C_right

In [32]:
C

array([500., 500., 500., 500., 500., 500., 500., 500., 500.,   0.,   0.,
         0.,   0.,   0.,   0.,   0.])

In [33]:
C[-1]

np.float64(0.0)

In [34]:
x[-1]

np.float64(7.5)

In [35]:
x[-2]

np.float64(7.0)

In [36]:
nx = len(x)
nx

16